  services:
    db:
      image: postgres:latest
      container_name: snappost_postgres
      restart: always
      environment:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    api:
      build: .
      container_name: snappost_api
      depends_on:
        - db
      environment:
        DATABASE_URL: $DATABASE_URL
        POSTGRES_HOST: $POSTGRES_HOST
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_PORT: 5432
        FASTAPI_PORT: 8000
        SECRET_KEY: ${SECRET_KEY}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
        ALGORITHM: ${ALGORITHM}
      ports:
        - "8000:8000"
      volumes:
        - .:/app

  volumes:
    postgres_data:
