  services:
    db:
      image: postgres:latest
      container_name: snappost_postgres
      restart: always
      environment:
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    api:
      build: .
      container_name: snappost_api
      depends_on:
        - db
        - minio
      environment:
        DATABASE_URL: $DOCKER_DATABASE_URL
        POSTGRES_HOST: $DOCKER_POSTGRES_HOST
        POSTGRES_USER: $POSTGRES_USER
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
        POSTGRES_PORT: 5432
        FASTAPI_PORT: 8000
        SECRET_KEY: ${SECRET_KEY}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
        ALGORITHM: ${ALGORITHM}
        MINIO_ENDPOINT: ${MINIO_ENDPOINT}
        MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
        MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      ports:
        - "8000:8000"
      volumes:
        - .:/app

    minio:
      image: minio/minio
      container_name: minio
      environment:
        MINIO_ROOT_USER: $MINIO_ROOT_USER
        MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      volumes:
        - minio_data:/data
      ports:
        - "9000:9000"
        - "9001:9001"
      command: server --console-address ":9001" /data

  volumes:
    postgres_data:
    minio_data:
