"""filename added to Post Model

Revision ID: 73220500ad4a
Revises: ce943c7a286f
Create Date: 2025-09-21 17:10:05.421829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '73220500ad4a'
down_revision: Union[str, Sequence[str], None] = 'ce943c7a286f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'filename')
    # ### end Alembic commands ###
