"""post models created

Revision ID: bec46601fb3d
Revises: c253843e91d7
Create Date: 2025-09-14 15:49:48.419337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec46601fb3d'
down_revision: Union[str, Sequence[str], None] = 'c253843e91d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.drop_column('post', 'view')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('view', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('post', 'owner_id')
    # ### end Alembic commands ###
